# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "GPF"
version = "2025.29.29"
license = "Primarily MIT and PD"
author = "John S. Urban and GPF maintainers"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021,2025 John S. Urban"
description = "GPF (General Purpose Fortran)"
categories = ["fortran", "POSIX"]
keywords = ["fortran", "POSIX", "graphics", "strings", "unit tests"]
homepage = "https://github.com/urbanjost/GPF"
[build]
   link = ["curl", "ncurses", "sqlite3", "readline", "X11"]
   auto-executables = true
   auto-tests = true
   auto-examples = true

   # new force module naming rules to avoid collisions with other packages
   #module-naming = true
   # traditional where user can use any module name
   #module-naming = false
# new
[fortran]
   implicit-typing = false
   implicit-external = true
   source-form = "free"
   # traditional pre-version8 compatibility
   #implicit-typing = true
   #implicit-external = true
   #source-form = "default"
[install]
   library = true
