#!/bin/bash
#@(#)mank(1sh): list the manual page names and descriptions found in this distribution
MANPATH=$(dirname $0)/../man:$HOME/LIBRARY/libjust4/download/tmp/man

export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m')     # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m')     # leave standout mode    
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
export LESS_TERMCAP_ue=$(printf '\e[0m')     # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan

if [ "$*" = '' ]
then
   if [ -t 1 ]  # if stdout is a terminal and no parameters create man page index and edit it
   then
      TFILE=/tmp/$(uuidgen)
      cat > $TFILE <<EOF
================================================================================
   NOTES:
     vim(1) editor users can place the cursor on a topic name and press "K" to display
     the corresponding man(1) page
================================================================================
EOF
      man -k .|
      env LC_ALL=C /usr/bin/sort|uniq|cat -n >> $TFILE
      EDIT=${FCEDIT:-${EDITOR:-${VISUAL:-vim}}}
      $EDIT $TFILE
      rm $TFILE
   else
      man -k .|env LC_ALL=C /usr/bin/sort|uniq|cat -n|more
   fi
else
   man $*
fi
#SEE ALSO: apropos
exit
