name: msys windows gfortran

on: [push, pull_request]

env:
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever
  FC: gfortran
  TZ: UTC+04:00

jobs:
  gfortran-windows-msys2-mingw64:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup MinGW (MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          git
          wget
          mingw-w64-x86_64-gcc-fortran

    - name: Install fpm
      shell: msys2 {0}
      run: |
           wget https://raw.githubusercontent.com/lockstockandbarrel/mars/main/bootstrap/fpm.F90
           mkdir tmp
           gfortran fpm.F90 -Jtmp -Itmp -static -o fpm
           rm -f tmp/*.mod

    - name: Run tests and demo programs (debug)
      shell: msys2 {0}
      run: |
        gfortran --version
        ./fpm test --profile release -flag "-D _WIN32"
      env:
         FC: gfortran
         TZ: UTC+04:00

    - name: Run tests and demo programs (release)
      shell: msys2 {0}
      run: |
        gfortran --version
        ./fpm test --profile release -flag "-D _WIN32"
      env:
         FC: gfortran
         TZ: UTC+04:00

    - name: cleanup 
      run: dir
