# Workflow for continuous integration tests

# wget https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7_21.7_amd64.deb
# https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-2021_21.7_amd64.deb
# apt-get install ./nvhpc-21-7_21.7_amd64.deb ./nvhpc-2021_21.7_amd64.deb

name: test fpm on ubuntu with nvfortran
on: [push, pull_request]

jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        fortran-compiler: [nvfortran]
    env:
      F90: nvfortran
      FC:  nvfortran
      F90FLAGS: "-O3 -ffree-line-length-none -fcheck=bounds -finit-real=nan"
      ATOL: 0.0
      RTOL: 0.0
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    ###############################################################################
    # Initial steps
    ###############################################################################
    #
    # Nvidia compilers
    #
    - name: Nvidia setup compilers
      env:
        NVCOMPILERS: /opt/nvidia/hpc_sdk
      run: |
        wget https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7_21.7_amd64.deb https://developer.download.nvidia.com/hpc-sdk/21.7/nvhpc-21-7_21.7_amd64.deb
        sudo apt-get install ./nvhpc-21-7_21.7_amd64.deb ./nvhpc-2021_21.7_amd64.deb
    ###############################################################################
    # Compiler-specific environment
    ###############################################################################
    # Environment for nvidia compilers
    - name: Environment for nvfortran compiler
      env:
        NVCOMPILERS: /opt/nvidia/hpc_sdk
      if: contains(matrix.fortran-compiler, 'nvfortran')
      run: |
        echo "::set-env name=CC::nvc"
        echo "::set-env name=FC::nvfortran"
        echo "::set-env name=F90FLAGS::"
        echo "::add-path::${NVCOMPILERS}/Linux_x86_64/20.7/compilers/bin"
    ###############################################################################
    - name: run nvfortran
      run: nvfortran --version
