name: fpm test on windows mingw with gfortran

on: [push, pull_request]

env:
  CTEST_TIME_TIMEOUT: "50"  # some failures hang forever

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    env:
      FC: gfortran
      TZ: UTC+04:00
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2

    - name: Setup MinGW native environment
      uses: msys2/setup-msys2@v2
      if: contains(matrix.msystem, 'MINGW')
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          git
          wget
          mingw-w64-${{ matrix.arch }}-gcc
          mingw-w64-${{ matrix.arch }}-gcc-fortran

    - name: Install fpm
      run: |
        wget https://github.com/awvwgk/mingw-w64-fpm-pkgbuild/releases/download/current/mingw-w64-x86_64-fpm-0.2.0-1-any.pkg.tar.zst
        pacman -U --noconfirm mingw-w64-x86_64-fpm-*-any.pkg.tar.zst

    - run: |
        gfortran --version
        fpm test --compiler gfortran --profile release -flag "-D _WIN32"
    - run: |
        gfortran --version
        fpm test --compiler gfortran --profile debug   -flag "-D _WIN32"
      env:
        FPM_COMPILER: gfortran
        CC: gcc
        CXX: g++
