#!/bin/sh
# @(#)banner.sh 1.0 emulate banner command 19940301 John S. Urban
ONECHAR(){
CHAR="$*"
case "$CHAR" in
A)
echo '________'
echo '________'
echo '___XX___'
echo '____X___'
echo '____X___'
echo '___X_X__'
echo '___X_X__'
echo '__X___X_'
echo '__XXXXX_'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
B)
echo '________'
echo '________'
echo '_XXXXXX_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__XXXXX_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '_XXXXXX_'
echo '________'
echo '________'
;;
C)
echo '________'
echo '________'
echo '___XXXX_'
echo '__X____X'
echo '_X______'
echo '_X______'
echo '_X______'
echo '_X______'
echo '_X______'
echo '__X____X'
echo '___XXXX_'
echo '________'
echo '________'
;;
D)
echo '________'
echo '________'
echo '_XXXXX__'
echo '__X___X_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__X___X_'
echo '_XXXXX__'
echo '________'
echo '________'
;;
E)
echo '________'
echo '________'
echo '_XXXXXXX'
echo '__X____X'
echo '__X_____'
echo '__X__X__'
echo '__XXXX__'
echo '__X__X__'
echo '__X_____'
echo '__X____X'
echo '_XXXXXXX'
echo '________'
echo '________'
;;
F)
echo '________'
echo '________'
echo '_XXXXXXX'
echo '__X____X'
echo '__X_____'
echo '__X__X__'
echo '__XXXX__'
echo '__X__X__'
echo '__X_____'
echo '__X_____'
echo '_XXXX___'
echo '________'
echo '________'
;;
G)
echo '________'
echo '________'
echo '___XXXX_'
echo '__X____X'
echo '_X______'
echo '_X______'
echo '_X______'
echo '_X___XXX'
echo '_X_____X'
echo '__X____X'
echo '___XXXX_'
echo '________'
echo '________'
;;
H)
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__XXXXX_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
I)
echo '________'
echo '________'
echo '__XXXXX_'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '__XXXXX_'
echo '________'
echo '________'
;;
J)
echo '________'
echo '________'
echo '___XXXX_'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_X___X__'
echo '_X___X__'
echo '__XXX___'
echo '________'
echo '________'
;;
G)
echo '________'
echo '________'
echo '___XXXX_'
echo '__X____X'
echo '_X______'
echo '_X______'
echo '_X______'
echo '_X___XXX'
echo '_X_____X'
echo '__X____X'
echo '___XXXX_'
echo '________'
echo '________'
;;
K)
echo '________'
echo '________'
echo '_XXX__XX'
echo '__X___X_'
echo '__X__X__'
echo '__X__X__'
echo '__X_X___'
echo '__XXX___'
echo '__X__X__'
echo '__X___X_'
echo '_XXX__XX'
echo '________'
echo '________'
;;
L)
echo '________'
echo '________'
echo '_XXXXX__'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X___X'
echo '_XXXXXXX'
echo '________'
echo '________'
;;
M)
echo '________'
echo '________'
echo '_XX___XX'
echo '__X___X_'
echo '__XX_XX_'
echo '__XX_XX_'
echo '__X_X_X_'
echo '__X_X_X_'
echo '__X___X_'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
N)
echo '________'
echo '________'
echo '_XX__XXX'
echo '__X___X_'
echo '__XX__X_'
echo '__XX__X_'
echo '__X_X_X_'
echo '__X__XX_'
echo '__X__XX_'
echo '__X___X_'
echo '_XXX__X_'
echo '________'
echo '________'
;;
O)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
P)
echo '________'
echo '________'
echo '_XXXXXX_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__XXXXX_'
echo '__X_____'
echo '__X_____'
echo '__X_____'
echo '_XXXX___'
echo '________'
echo '________'
;;
Q)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '__X___X_'
echo '___XXX__'
echo '___XX_XX'
echo '________'
;;
R)
echo '________'
echo '________'
echo '_XXXXXX_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__XXXXX_'
echo '__X__X__'
echo '__X__X__'
echo '__X___X_'
echo '_XXX__XX'
echo '________'
echo '________'
;;
S)
echo '________'
echo '________'
echo '__XXXXX_'
echo '_X_____X'
echo '_X______'
echo '_X______'
echo '__XXXXX_'
echo '_______X'
echo '_______X'
echo '_X_____X'
echo '__XXXXX_'
echo '________'
echo '________'
;;
T)
echo '________'
echo '________'
echo '_XXXXXXX'
echo '_X__X__X'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '___XXX__'
echo '________'
echo '________'
;;
U)
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
V)
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___X_X__'
echo '___X_X__'
echo '___X_X__'
echo '____X___'
echo '____X___'
echo '________'
echo '________'
;;
W)
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X_X_X_'
echo '__X_X_X_'
echo '__X_X_X_'
echo '___X_X__'
echo '___X_X__'
echo '________'
echo '________'
;;
X)
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '___X_X__'
echo '___X_X__'
echo '____X___'
echo '___X_X__'
echo '___X_X__'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
Y)
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '___X_X__'
echo '___X_X__'
echo '____X___'
echo '____X___'
echo '____X___'
echo '___XXX__'
echo '________'
echo '________'
;;
Z)
echo '________'
echo '________'
echo '_XXXXXXX'
echo '_X____X_'
echo '_____X__'
echo '_____X__'
echo '____X___'
echo '___X____'
echo '___X____'
echo '__X____X'
echo '_XXXXXXX'
echo '________'
echo '________'
;;
a)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXX__'
echo '______X_'
echo '__XXXXX_'
echo '_X____X_'
echo '_X____X_'
echo '__XXXX_X'
echo '________'
echo '________'
;;
b)
echo '________'
echo '________'
echo '_XX_____'
echo '__X_____'
echo '__X_____'
echo '__XXXXX_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '_XXXXXX_'
echo '________'
echo '________'
;;
c)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXX_'
echo '_X_____X'
echo '_X______'
echo '_X______'
echo '_X_____X'
echo '__XXXXX_'
echo '________'
echo '________'
;;
d)
echo '________'
echo '________'
echo '_____XX_'
echo '______X_'
echo '______X_'
echo '__XXXXX_'
echo '_X____X_'
echo '_X____X_'
echo '_X____X_'
echo '_X____X_'
echo '__XXXXXX'
echo '________'
echo '________'
;;
e)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXX_'
echo '_X_____X'
echo '_XXXXXXX'
echo '_X______'
echo '_X_____X'
echo '__XXXXX_'
echo '________'
echo '________'
;;
f)
echo '________'
echo '________'
echo '____XX__'
echo '___X____'
echo '___X____'
echo '__XXXX__'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '__XXXX__'
echo '________'
echo '________'
;;
g)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXXX'
echo '_X____X_'
echo '_X____X_'
echo '_X____X_'
echo '__XXXXX_'
echo '______X_'
echo '______X_'
echo '__XXXX__'
;;
h)
echo '________'
echo '________'
echo '_XX_____'
echo '__X_____'
echo '__X_____'
echo '__X_XX__'
echo '__XX__X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
i)
echo '________'
echo '________'
echo '____X___'
echo '________'
echo '________'
echo '__XXX___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '__XXXXX_'
echo '________'
echo '________'
;;
j)
echo '________'
echo '________'
echo '_____X__'
echo '________'
echo '________'
echo '__XXXX__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '__XXX___'
;;
g)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXXX'
echo '_X____X_'
echo '_X____X_'
echo '_X____X_'
echo '__XXXXX_'
echo '______X_'
echo '______X_'
echo '__XXXX__'
;;
k)
echo '________'
echo '________'
echo '_XX_____'
echo '__X_____'
echo '__X_____'
echo '__X__XX_'
echo '__X__X__'
echo '__X_X___'
echo '__XXX___'
echo '__X__X__'
echo '_XX___XX'
echo '________'
echo '________'
;;
l)
echo '________'
echo '________'
echo '___XX___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '__XXXXX_'
echo '________'
echo '________'
;;
m)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXX_X__'
echo '__X_X_X_'
echo '__X_X_X_'
echo '__X_X_X_'
echo '__X_X_X_'
echo '_XX_X_XX'
echo '________'
echo '________'
;;
n)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XX_XX__'
echo '__XX__X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
o)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXX_'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '_X_____X'
echo '__XXXXX_'
echo '________'
echo '________'
;;
p)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXXXXX_'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__X____X'
echo '__XXXXX_'
echo '__X_____'
echo '_XXX____'
;;
q)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXXX'
echo '_X____X_'
echo '_X____X_'
echo '_X____X_'
echo '_X____X_'
echo '__XXXXX_'
echo '______X_'
echo '_____XXX'
;;
r)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXX_XX_'
echo '___XX__X'
echo '___X____'
echo '___X____'
echo '___X____'
echo '_XXXXX__'
echo '________'
echo '________'
;;
s)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXX_'
echo '_X_____X'
echo '__XXX___'
echo '_____XX_'
echo '_X_____X'
echo '__XXXXX_'
echo '________'
echo '________'
;;
t)
echo '________'
echo '________'
echo '________'
echo '___X____'
echo '___X____'
echo '__XXXX__'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X__X_'
echo '____XX__'
echo '________'
echo '________'
;;
u)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XX__XX_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X__XX_'
echo '___XX_XX'
echo '________'
echo '________'
;;
v)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '___X_X__'
echo '___X_X__'
echo '____X___'
echo '________'
echo '________'
;;
w)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X_X_X_'
echo '__X_X_X_'
echo '___X_X__'
echo '___X_X__'
echo '________'
echo '________'
;;
x)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '___XXX__'
echo '___XXX__'
echo '__X___X_'
echo '_XXX_XXX'
echo '________'
echo '________'
;;
y)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXX_XXX'
echo '__X___X_'
echo '__X___X_'
echo '___X_X__'
echo '___X_X__'
echo '____X___'
echo '____X___'
echo '__XX____'
;;
z)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXXXXX_'
echo '_X___X__'
echo '____X___'
echo '___X____'
echo '__X___X_'
echo '_XXXXXX_'
echo '________'
echo '________'
;;
1)
echo '________'
echo '________'
echo '____X___'
echo '__XXX___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '__XXXXX_'
echo '________'
echo '________'
;;
2)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '______X_'
echo '______X_'
echo '_____X__'
echo '____X___'
echo '___X____'
echo '__X_____'
echo '__XXXXX_'
echo '________'
echo '________'
;;
3)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '______X_'
echo '______X_'
echo '____XX__'
echo '______X_'
echo '______X_'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
4)
echo '________'
echo '________'
echo '_____X__'
echo '____XX__'
echo '____XX__'
echo '___X_X__'
echo '___X_X__'
echo '__X__X__'
echo '__XXXXX_'
echo '_____X__'
echo '____XXX_'
echo '________'
echo '________'
;;
5)
echo '________'
echo '________'
echo '__XXXXX_'
echo '__X_____'
echo '__X_____'
echo '__X_____'
echo '__XXXX__'
echo '______X_'
echo '______X_'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
6)
echo '________'
echo '________'
echo '____XX__'
echo '___X____'
echo '__X_____'
echo '__X_____'
echo '__XXXX__'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
7)
echo '________'
echo '________'
echo '__XXXXX_'
echo '__X___X_'
echo '______X_'
echo '_____X__'
echo '_____X__'
echo '____X___'
echo '____X___'
echo '___X____'
echo '___X____'
echo '________'
echo '________'
;;
8)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___XXX__'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
9)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___XXXX_'
echo '______X_'
echo '______X_'
echo '_____X__'
echo '___XX___'
echo '________'
echo '________'
;;
0)
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '__X___X_'
echo '___XXX__'
echo '________'
echo '________'
;;
' ')
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
'`')
echo '________'
echo '________'
echo '___X____'
echo '____X___'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
'~')
echo '________'
echo '________'
echo '________'
echo '__XX___X'
echo '_X__X__X'
echo '_X___XX_'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
!)
echo '________'
echo '________'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '________'
echo '____X___'
echo '________'
echo '________'
;;
@)
echo '________'
echo '________'
echo '___XXXX_'
echo '__X____X'
echo '_X__XX_X'
echo '_X_X_X_X'
echo '_X_X_X_X'
echo '_X_X_X_X'
echo '_X__XXX_'
echo '__X_____'
echo '___XXX__'
echo '________'
echo '________'
;;
'#')
echo '________'
echo '________'
echo '____X_X_'
echo '____X_X_'
echo '__XXXXXX'
echo '___X_X__'
echo '___X_X__'
echo '___X_X__'
echo '_XXXXXX_'
echo '__X_X___'
echo '__X_X___'
echo '________'
echo '________'
;;
'$')
echo '________'
echo '________'
echo '____X___'
echo '___XXX__'
echo '__X___X_'
echo '__X_____'
echo '___XXX__'
echo '______X_'
echo '__X___X_'
echo '___XXX__'
echo '____X___'
echo '________'
echo '________'
;;
%)
echo '________'
echo '________'
echo '__X_____'
echo '_X_X___X'
echo '__X___X_'
echo '_____X__'
echo '____X___'
echo '___X____'
echo '__X___X_'
echo '_X___X_X'
echo '______X_'
echo '________'
echo '________'
;;
'^')
echo '________'
echo '____X___'
echo '___X_X__'
echo '__X___X_'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
'&')
echo '________'
echo '________'
echo '___XX___'
echo '__X_____'
echo '__X_____'
echo '___X____'
echo '__XX____'
echo '_X__X__X'
echo '_X__X_X_'
echo '_X___X__'
echo '__XXX_XX'
echo '________'
echo '________'
;;
'*')
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XX_XX_'
echo '___XXX__'
echo '_XXXXXXX'
echo '___XXX__'
echo '__XX_XX_'
echo '________'
echo '________'
echo '________'
echo '________'
;;
'(')
echo '________'
echo '________'
echo '_____X__'
echo '____X___'
echo '____X___'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '____X___'
echo '____X___'
echo '_____X__'
;;
')')
echo '________'
echo '________'
echo '___X____'
echo '____X___'
echo '____X___'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '____X___'
echo '____X___'
echo '___X____'
;;
'-')
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '_XXXXXXX'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
_)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo 'XXXXXXXX'
;;
=)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '__XXXXX_'
echo '________'
echo '__XXXXX_'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
+)
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '____X___'
echo '____X___'
echo '_XXXXXXX'
echo '____X___'
echo '____X___'
echo '____X___'
echo '________'
echo '________'
;;
'[')
echo '________'
echo '________'
echo '___XXX__'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___X____'
echo '___XXX__'
;;
']')
echo '________'
echo '________'
echo '___XXX__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '_____X__'
echo '___XXX__'
;;
'{')
echo '________'
echo '________'
echo '_____XX_'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '__XX____'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '_____XX_'
;;
'}')
echo '________'
echo '________'
echo '__XX____'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '_____XX_'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '__XX____'
;;
'\')
echo '________'
echo '________'
echo '________'
echo '_X______'
echo '__X_____'
echo '___X____'
echo '____X___'
echo '_____X__'
echo '______X_'
echo '_______X'
echo '________'
echo '________'
echo '________'
;;
'|')
echo '________'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
echo '____X___'
;;
"'")
echo '________'
echo '________'
echo '____X___'
echo '____X___'
echo '____X___'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
';')
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '___X____'
echo '________'
;;
':')
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '________'
echo '________'
;;
'"')
echo '________'
echo '________'
echo '___X_X__'
echo '___X_X__'
echo '___X_X__'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
,)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '___X____'
echo '________'
;;
.)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '____X___'
echo '________'
echo '________'
;;
/)
echo '________'
echo '________'
echo '________'
echo '_______X'
echo '______X_'
echo '_____X__'
echo '____X___'
echo '___X____'
echo '__X_____'
echo '_X______'
echo '________'
echo '________'
echo '________'
;;
'<')
echo '________'
echo '________'
echo '________'
echo '________'
echo '_____X__'
echo '____X___'
echo '___X____'
echo '__X_____'
echo '___X____'
echo '____X___'
echo '_____X__'
echo '________'
echo '________'
;;
'>')
echo '________'
echo '________'
echo '________'
echo '________'
echo '___X____'
echo '____X___'
echo '_____X__'
echo '______X_'
echo '_____X__'
echo '____X___'
echo '___X____'
echo '________'
echo '________'
;;
'?')
echo '________'
echo '________'
echo '___XXX__'
echo '__X___X_'
echo '______X_'
echo '______X_'
echo '_____X__'
echo '____X___'
echo '____X___'
echo '________'
echo '____X___'
echo '________'
echo '________'
;;
*)
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
echo '________'
;;
*)
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
echo 'XXXXXXXX'
;;
esac
}
#for CHAR in \A \B \C \D \E \F \G \H \I \J \G \K \L \M \N \O \P \Q \R \S \T \U \V \W \X \Y \Z \a \b \c \d \e \f \g \h \i \j \g \k \l \m \n \o \p \q \r \s \t \u \v \w \x \y \z \1 \2 \3 \4 \5 \6 \7 \8 \9 \0 \  \` \~ \! \@ \# \$ \% \^ \& \* \( \) \- \_ \= \+ \[ \] \{ \} \\ \| \' \; \: \" \, \. \/ \< \> \?
while [ "$1" != '' ]
do
for CHAR in `echo "$1"|tr ' ' '\019'|sed -e 's/./ &/g'`
do
ONECHAR "$CHAR"
done|( while read LINE
do
           LINEa="${LINEa}${LINE}"
read LINE; LINEb="${LINEb}${LINE}"
read LINE; LINEc="${LINEc}${LINE}"
read LINE; LINEd="${LINEd}${LINE}"
read LINE; LINEe="${LINEe}${LINE}"
read LINE; LINEf="${LINEf}${LINE}"
read LINE; LINEg="${LINEg}${LINE}"
read LINE; LINEh="${LINEh}${LINE}"
read LINE; LINEi="${LINEi}${LINE}"
read LINE; LINEj="${LINEj}${LINE}"
read LINE; LINEk="${LINEk}${LINE}"
read LINE; LINEl="${LINEl}${LINE}"
read LINE; LINEm="${LINEm}${LINE}"
done

echo "${LINEa}"
echo "${LINEb}"
echo "${LINEc}"
echo "${LINEd}"
echo "${LINEe}"
echo "${LINEf}"
echo "${LINEg}"
echo "${LINEh}"
echo "${LINEi}"
echo "${LINEj}"
echo "${LINEk}"
echo "${LINEl}"
echo "${LINEm}"
) | tr '_' ' '
shift
done
exit
