module M_blas
use, intrinsic :: iso_fortran_env, only : int8, int16, int32, int64, real32, real64, real128
!==============================================================================
! xerbla needs a special version for the test programs to run
! so it is a pointer to the standard procedure, but allows for
! xerbla to point to a user-defined procedure for testing
!
!    use M_blas, only : set_xerbla, std_xerbla
!    call set_mysub(SUBROUTINE_NAME)
public  :: xerbla
public  :: set_xerbla
private :: std_xerbla
public  :: xerbla_interface

abstract interface
   subroutine xerbla_interface(srname,info)
      character(len=*),intent(in)          :: srname
      integer,intent(in)                   :: info
   end subroutine xerbla_interface
end interface

procedure(xerbla_interface),pointer :: xerbla => std_xerbla
!==============================================================================
contains
subroutine set_xerbla(proc)
procedure(xerbla_interface) :: proc
   xerbla => proc
end subroutine set_xerbla
INCLUDE "xerbla_array.finc"
INCLUDE "xerbla.finc"
INCLUDE "caxpy.finc"
INCLUDE "ccopy.finc"
INCLUDE "cdotc.finc"
INCLUDE "cdotu.finc"
INCLUDE "cgbmv.finc"
INCLUDE "cgemm.finc"
INCLUDE "cgemv.finc"
INCLUDE "cgerc.finc"
INCLUDE "cgeru.finc"
INCLUDE "chbmv.finc"
INCLUDE "chemm.finc"
INCLUDE "chemv.finc"
INCLUDE "cher2.finc"
INCLUDE "cher2k.finc"
INCLUDE "cher.finc"
INCLUDE "cherk.finc"
INCLUDE "chpmv.finc"
INCLUDE "chpr2.finc"
INCLUDE "chpr.finc"
INCLUDE "crotg.finc"
INCLUDE "cscal.finc"
INCLUDE "csrot.finc"
INCLUDE "csscal.finc"
INCLUDE "cswap.finc"
INCLUDE "csymm.finc"
INCLUDE "csyr2k.finc"
INCLUDE "csyrk.finc"
INCLUDE "ctbmv.finc"
INCLUDE "ctbsv.finc"
INCLUDE "ctpmv.finc"
INCLUDE "ctpsv.finc"
INCLUDE "ctrmm.finc"
INCLUDE "ctrmv.finc"
INCLUDE "ctrsm.finc"
INCLUDE "ctrsv.finc"
INCLUDE "dasum.finc"
INCLUDE "daxpy.finc"
INCLUDE "dcabs1.finc"
INCLUDE "dcopy.finc"
INCLUDE "ddot.finc"
INCLUDE "dgbmv.finc"
INCLUDE "dgemm.finc"
INCLUDE "dgemv.finc"
INCLUDE "dger.finc"
INCLUDE "dnrm2.finc"
INCLUDE "drot.finc"
INCLUDE "drotg.finc"
INCLUDE "drotm.finc"
INCLUDE "drotmg.finc"
INCLUDE "dsbmv.finc"
INCLUDE "dscal.finc"
INCLUDE "dsdot.finc"
INCLUDE "dspmv.finc"
INCLUDE "dspr2.finc"
INCLUDE "dspr.finc"
INCLUDE "dswap.finc"
INCLUDE "dsymm.finc"
INCLUDE "dsymv.finc"
INCLUDE "dsyr2.finc"
INCLUDE "dsyr2k.finc"
INCLUDE "dsyr.finc"
INCLUDE "dsyrk.finc"
INCLUDE "dtbmv.finc"
INCLUDE "dtbsv.finc"
INCLUDE "dtpmv.finc"
INCLUDE "dtpsv.finc"
INCLUDE "dtrmm.finc"
INCLUDE "dtrmv.finc"
INCLUDE "dtrsm.finc"
INCLUDE "dtrsv.finc"
INCLUDE "dzasum.finc"
INCLUDE "dznrm2.finc"
INCLUDE "icamax.finc"
INCLUDE "idamax.finc"
INCLUDE "isamax.finc"
INCLUDE "izamax.finc"
INCLUDE "lsame.finc"
INCLUDE "sasum.finc"
INCLUDE "saxpy.finc"
INCLUDE "scabs1.finc"
INCLUDE "scasum.finc"
INCLUDE "scnrm2.finc"
INCLUDE "scopy.finc"
INCLUDE "sdot.finc"
INCLUDE "sdsdot.finc"
INCLUDE "sgbmv.finc"
INCLUDE "sgemm.finc"
INCLUDE "sgemv.finc"
INCLUDE "sger.finc"
INCLUDE "snrm2.finc"
INCLUDE "srot.finc"
INCLUDE "srotg.finc"
INCLUDE "srotm.finc"
INCLUDE "srotmg.finc"
INCLUDE "ssbmv.finc"
INCLUDE "sscal.finc"
INCLUDE "sspmv.finc"
INCLUDE "sspr2.finc"
INCLUDE "sspr.finc"
INCLUDE "sswap.finc"
INCLUDE "ssymm.finc"
INCLUDE "ssymv.finc"
INCLUDE "ssyr2.finc"
INCLUDE "ssyr2k.finc"
INCLUDE "ssyr.finc"
INCLUDE "ssyrk.finc"
INCLUDE "stbmv.finc"
INCLUDE "stbsv.finc"
INCLUDE "stpmv.finc"
INCLUDE "stpsv.finc"
INCLUDE "strmm.finc"
INCLUDE "strmv.finc"
INCLUDE "strsm.finc"
INCLUDE "strsv.finc"
INCLUDE "zaxpy.finc"
INCLUDE "zcopy.finc"
INCLUDE "zdotc.finc"
INCLUDE "zdotu.finc"
INCLUDE "zdrot.finc"
INCLUDE "zdscal.finc"
INCLUDE "zgbmv.finc"
INCLUDE "zgemm.finc"
INCLUDE "zgemv.finc"
INCLUDE "zgerc.finc"
INCLUDE "zgeru.finc"
INCLUDE "zhbmv.finc"
INCLUDE "zhemm.finc"
INCLUDE "zhemv.finc"
INCLUDE "zher2.finc"
INCLUDE "zher2k.finc"
INCLUDE "zher.finc"
INCLUDE "zherk.finc"
INCLUDE "zhpmv.finc"
INCLUDE "zhpr2.finc"
INCLUDE "zhpr.finc"
INCLUDE "zrotg.finc"
INCLUDE "zscal.finc"
INCLUDE "zswap.finc"
INCLUDE "zsymm.finc"
INCLUDE "zsyr2k.finc"
INCLUDE "zsyrk.finc"
INCLUDE "ztbmv.finc"
INCLUDE "ztbsv.finc"
INCLUDE "ztpmv.finc"
INCLUDE "ztpsv.finc"
INCLUDE "ztrmm.finc"
INCLUDE "ztrmv.finc"
INCLUDE "ztrsm.finc"
INCLUDE "ztrsv.finc"
end module M_blas
